### PR TITLE
Update release.js

### PR DESCRIPTION
**Pull request by fritzvd**
We like to have an adaptable release tag.. Instead of release-v%VERSION%

### CODE REVIEW

**Comment by boennemann** [comment]
Hey @fritzvd,

sorry for the late answer and thanks for the PR. Could you explain why you want to change the tag format, as it's only temporary and meant to be deleted right away.

No worries I'm up for this PR, I just want to make sense of it first.

Best,
Stephan

**Comment by fritzvd** [comment]
Hi Stephan,

As I understood it the tags were also being sent to github. So yes they may
be deleted locally, but on Github in the release/tags section they show up
in a format we don't usually use at the company I work for.
Or am I just misunderstanding this part? (might also be.)

Fritz

On 4 November 2014 10:57, Stephan Bönnemann notifications@github.com
wrote:

> Hey @fritzvd https://github.com/fritzvd,
> 
> sorry for the late answer and thanks for the PR. Could you explain why you
> want to change the tag format, as it's only temporary and meant to be
> deleted right away.
> 
> No worries I'm up for this PR, I just want to make sense of it first.
> 
> Best,
> Stephan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/boennemann/grunt-semantic-release/pull/17#issuecomment-61616693
> .

## 

*Nelen & Schuurmans *

 Postbus 1219  3500 BE Utrecht
Zakkendragershof 34-44 Utrecht
tel. 030 2330 200
@fritzvd http://twitter.com/fritzvd
www.nelen-schuurmans.nl

**Comment by boennemann** [comment]
They're created locally, pushed to Github and then deleted locally.
Travis picks it up from there and deletes the tag from Github as soon as it starts work.

So no they do not show up anywhere, once the version is released :)

**Comment by fritzvd** [comment]
Ah. Right.

There's the problem, I didn't connect Travis to it. We're using Jenkins.
Anyways you can just close and forget about this then, :smile:.
And we'll figure out another to release a version and push it to GH. As
we're using the GH tags as release versions.

Thanks anyways,

fritz

On 4 November 2014 11:05, Stephan Bönnemann notifications@github.com
wrote:

> They're created locally, pushed to Github and then deleted locally.
> Travis picks it up from there and deletes the tag from Github as soon as
> it starts work.
> 
> So no they do not show up anywhere, once the version is released :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/boennemann/grunt-semantic-release/pull/17#issuecomment-61617603
> .

## 

*Nelen & Schuurmans *

 Postbus 1219  3500 BE Utrecht
Zakkendragershof 34-44 Utrecht
tel. 030 2330 200
@fritzvd http://twitter.com/fritzvd
www.nelen-schuurmans.nl

**Pull request closed without merging**
